CREATE DATABASE IF NOT EXISTS VirusTester;

CREATE TABLE VirusTester.users (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  admin BOOLEAN DEFAULT 0
);

CREATE TABLE VirusTester.viruses (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  signature VARCHAR(255) NOT NULL UNIQUE
);
